knowage:

  tag: 7.4.5

  # 
  # Install a db with sample data
  # 
  installSampleData: true

  # 
  # Set the external URL of knowage.
  # 
  # Used to set HTTP headers of the internal proxy.
  # 
  completeExternalUrl: "http://localhost:8080"

  # 
  # Databases properties.
  # 
  db:
    user:     "knowage"
    pass:     # Optional : random value if not provided 
    rootPass: # Optional : random value if not provided 
    name:     "knowage_master"
  cache:
    user:     "knowage"
    pass:     # Optional : random value if not provided 
    rootPass: # Optional : random value if not provided 
    name:     "knowage_cache"
  
  # 
  # Security properties.
  # 
  hmac:                     # Optional : random value if not provided 
  passwordEncryptionSecret: # Optional : random value if not provided 

  # 
  # Technical stuff
  # 
  deployIngress: false
  
  deployCustomReverseProxy: false

  storageClass: default

  # 
  # Let the user uses a custom image.
  # 
  # Empty for default.
  # 
  customImageName:

  # 
  # Pull secret for private registry when using custom images
  #
  imagePullSecret:

  # 
  # Content of the services-whitelist.xml inside "/home/knowage/apache-tomcat/resources", for example:
  # 
  #   <WHITELIST>
  #           <service baseurl="https://www.youtube.com" />
  #           <service baseurl="https://vimeo.com" />
  #           <service baseurl="https://www.flickr.com" />
  #           <service baseurl="https://fonts.googleapis.com" />
  #           <service baseurl="https://code.highcharts.com" />
  #           <service relativepath="/knowage/themes/" />
  #           <service relativepath="/knowage/icons/" />
  #           <service relativepath="/knowage/dashboards/" />
  #   </WHITELIST>
  # 
  whitelist:
