#
# Knowage, Open Source Business Intelligence suite
# Copyright (C) 2022 Engineering Ingegneria Informatica S.p.A.
# 
# Knowage is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Knowage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

---
#  __  __          _____ _   _            _____  _____  
# |  \/  |   /\   |_   _| \ | |     /\   |  __ \|  __ \ 
# | \  / |  /  \    | | |  \| |    /  \  | |__) | |__) |
# | |\/| | / /\ \   | | | . ` |   / /\ \ |  ___/|  ___/ 
# | |  | |/ ____ \ _| |_| |\  |  / ____ \| |    | |     
# |_|  |_/_/    \_\_____|_| \_| /_/    \_\_|    |_|     
#                                                       
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knowage.config" . }}
  namespace: {{ .Release.Namespace }}
data:
  dbHost: {{ include "knowage.db.service" . | quote }}
  dbPort: {{ include "knowage.db.port" . | quote }}
  cacheDbHost: {{ include "knowage.cache.service" . | quote }}
  cacheDbPort: {{ include "knowage.cache.port" . | quote }}
  servicesWhitelist: |
    {{- if .Values.knowage.whitelist -}}
    {{- print .Values.knowage.whitelist | nindent 4 -}}
    {{ else }}
    <?xml version="1.0" encoding="UTF-8"?>
    <WHITELIST>
            <service baseurl="https://www.youtube.com" />
            <service baseurl="https://vimeo.com" />
            <service baseurl="https://www.flickr.com" />
            <service baseurl="https://fonts.googleapis.com" />
            <service baseurl="https://code.highcharts.com" />
            <service relativepath="/knowage/themes/" />
            <service relativepath="/knowage/icons/" />
            <service relativepath="/knowage/dashboards/" />
    </WHITELIST>
    {{- end }}
  tomcatUsers: |
    {{- if .Values.knowage.tomcatUsers -}}
    {{- print .Values.knowage.tomcatUsers | nindent 4 -}}
    {{ else }}
    <?xml version="1.0" encoding="UTF-8"?>
    <tomcat-users xmlns="http://tomcat.apache.org/xml"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
                  version="1.0">
    </tomcat-users>
    {{- end }}
  extGlobalResources: |
    {{- if .Values.knowage.extGlobalResources -}}
    {{- print .Values.knowage.extGlobalResources | nindent 4 -}}
    {{ else }}
    <!-- 
        Resources from server.xml.d/extGlobalRerouces.
        
        Copy the template from Knowage-Server-Docker/extGlobalRerouces, edit it and mount it as:
        
            /home/knowage/apache-tomcat/conf/server.xml.d/extGlobalRerouces
        
        To customize your server.xml with your resources. For example, you can
        add all the JDBC connections you need.
    -->

    <!-- <Resource
        auth="Container"
        driverClassName="com.mysql.jdbc.Driver"
        logAbandoned="true"
        maxTotal="20"
        maxIdle="4"
        maxWait="300"
        minEvictableIdleTimeMillis="60000"
        name="jdbc/foodmart"
        password="foodmart"
        removeAbandoned="true"
        removeAbandonedTimeout="3600"
        testOnReturn="true"
        testWhileIdle="true"
        timeBetweenEvictionRunsMillis="10000"
        type="javax.sql.DataSource"
        url="jdbc:mysql://foodmart:3306/foodmart"
        username="foodmart"/> -->
    {{- end }}
  extContext: |
    {{- if .Values.knowage.extContext -}}
    {{- print .Values.knowage.extContext | nindent 4 -}}
    {{ else }}
    <!-- 
        Resource links from context.xml.d/extContext.
        
        Copy the template from Knowage-Server-Docker/extContext, edit it and mount it as:
        
            /home/knowage/apache-tomcat/conf/context.xml.d/extContext
        
        To customize your context.xml with your resource links. For example, you can
        link all the JDBC connections you put into server.xml.d/extGlobalResources.
    -->

    <!-- <ResourceLink
      global="jdbc/foodmart"
      name="jdbc/foodmart"
      type="javax.sql.DataSource" /> -->
    {{- end }}

{{ if eq ( default .Values.knowage.deployHazelcast false ) true }}
---
#  _    _           ____________ _      _____           _____ _______ 
# | |  | |   /\    |___  /  ____| |    / ____|   /\    / ____|__   __|
# | |__| |  /  \      / /| |__  | |   | |       /  \  | (___    | |   
# |  __  | / /\ \    / / |  __| | |   | |      / /\ \  \___ \   | |   
# | |  | |/ ____ \  / /__| |____| |___| |____ / ____ \ ____) |  | |   
# |_|  |_/_/    \_\/_____|______|______\_____/_/    \_\_____/   |_|   
#                                                                     
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knowage.hazelcast.config" . }}
  namespace: {{ .Release.Namespace }}
data:
  hazelcast.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.6.xsd"
              xmlns="http://www.hazelcast.com/schema/config"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <network>
            <port auto-increment="false" port-count="100">5701</port>
            <join>
                <multicast enabled="false"></multicast>
                <tcp-ip enabled="true">
                    <member-list>
          <member>hazelcast</member>
        </member-list>
                </tcp-ip>
            </join>
        </network>
        <properties> 
          <property name="hazelcast.socket.bind.any">false</property>
        </properties>
    </hazelcast>
{{ end }}

{{ if or (eq ( default .Values.knowage.deployPython false ) true) (eq ( default .Values.knowage.python.deploy false ) true) }}
---
#  _______     _________ _    _  ____  _   _ 
# |  __ \ \   / /__   __| |  | |/ __ \| \ | |
# | |__) \ \_/ /   | |  | |__| | |  | |  \| |
# |  ___/ \   /    | |  |  __  | |  | | . ` |
# | |      | |     | |  | |  | | |__| | |\  |
# |_|      |_|     |_|  |_|  |_|\____/|_| \_|
#                                            
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knowage.python.config" . }}
  namespace: {{ .Release.Namespace }}
data:
  requirements.txt: |
{{- range $idx, $val := .Values.knowage.python.libraries }}
{{ print $val | indent 4 }}
{{- end }}
{{ end }}
