#
# Knowage, Open Source Business Intelligence suite
# Copyright (C) 2022 Engineering Ingegneria Informatica S.p.A.
# 
# Knowage is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Knowage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#  __  __          _____ _   _            _____  _____  
# |  \/  |   /\   |_   _| \ | |     /\   |  __ \|  __ \ 
# | \  / |  /  \    | | |  \| |    /  \  | |__) | |__) |
# | |\/| | / /\ \   | | | . ` |   / /\ \ |  ___/|  ___/ 
# | |  | |/ ____ \ _| |_| |\  |  / ____ \| |    | |     
# |_|  |_/_/    \_\_____|_| \_| /_/    \_\_|    |_|     
#                                                       
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knowage.config" . }}
  namespace: {{ .Release.Namespace }}
data:
  dbHost: {{ include "knowage.db.service" . | quote }}
  dbPort: {{ include "knowage.db.port" . | quote }}
  cacheDbHost: {{ include "knowage.cache.service" . | quote }}
  cacheDbPort: {{ include "knowage.cache.port" . | quote }}
  servicesWhitelist: |
    {{- if .Values.knowage.whitelist -}}
    {{- print .Values.knowage.whitelist | nindent 4 -}}
    {{ else }}
    <?xml version="1.0" encoding="UTF-8"?>
    <WHITELIST>
            <service baseurl="https://www.youtube.com" />
            <service baseurl="https://vimeo.com" />
            <service baseurl="https://www.flickr.com" />
            <service baseurl="https://fonts.googleapis.com" />
            <service baseurl="https://code.highcharts.com" />
            <service relativepath="/knowage/themes/" />
            <service relativepath="/knowage/icons/" />
            <service relativepath="/knowage/dashboards/" />
    </WHITELIST>
    {{- end }}
  tomcatUsers: |
    {{- if .Values.knowage.tomcatUsers -}}
    {{- print .Values.knowage.tomcatUsers | nindent 4 -}}
    {{ else }}
    <?xml version="1.0" encoding="UTF-8"?>
    <tomcat-users xmlns="http://tomcat.apache.org/xml"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
                  version="1.0">
    </tomcat-users>
    {{- end }}
  extGlobalResources: |
    {{- if .Values.knowage.extGlobalResources -}}
    {{- print .Values.knowage.extGlobalResources | nindent 4 -}}
    {{ else }}
    <!-- 
        Resources from server.xml.d/extGlobalRerouces.
        
        Copy the template from Knowage-Server-Docker/extGlobalRerouces, edit it and mount it as:
        
            /home/knowage/apache-tomcat/conf/server.xml.d/extGlobalRerouces
        
        To customize your server.xml with your resources. For example, you can
        add all the JDBC connections you need.
    -->

    <!-- <Resource
        auth="Container"
        driverClassName="com.mysql.jdbc.Driver"
        logAbandoned="true"
        maxTotal="20"
        maxIdle="4"
        maxWait="300"
        minEvictableIdleTimeMillis="60000"
        name="jdbc/foodmart"
        password="foodmart"
        removeAbandoned="true"
        removeAbandonedTimeout="3600"
        testOnReturn="true"
        testWhileIdle="true"
        timeBetweenEvictionRunsMillis="10000"
        type="javax.sql.DataSource"
        url="jdbc:mysql://foodmart:3306/foodmart"
        username="foodmart"/> -->
    {{- end }}
  extContext: |
    {{- if .Values.knowage.extContext -}}
    {{- print .Values.knowage.extContext | nindent 4 -}}
    {{ else }}
    <!-- 
        Resource links from context.xml.d/extContext.
        
        Copy the template from Knowage-Server-Docker/extContext, edit it and mount it as:
        
            /home/knowage/apache-tomcat/conf/context.xml.d/extContext
        
        To customize your context.xml with your resource links. For example, you can
        link all the JDBC connections you put into server.xml.d/extGlobalResources.
    -->

    <!-- <ResourceLink
      global="jdbc/foodmart"
      name="jdbc/foodmart"
      type="javax.sql.DataSource" /> -->
    {{- end }}

{{ if eq ( default .Values.knowage.deployCustomReverseProxy false ) true }}
#  _____  ________      ________ _____   _____ ______   _____  _____   ______   ____     __
# |  __ \|  ____\ \    / /  ____|  __ \ / ____|  ____| |  __ \|  __ \ / __ \ \ / /\ \   / /
# | |__) | |__   \ \  / /| |__  | |__) | (___ | |__    | |__) | |__) | |  | \ V /  \ \_/ / 
# |  _  /|  __|   \ \/ / |  __| |  _  / \___ \|  __|   |  ___/|  _  /| |  | |> <    \   /  
# | | \ \| |____   \  /  | |____| | \ \ ____) | |____  | |    | | \ \| |__| / . \    | |   
# |_|  \_\______|   \/   |______|_|  \_\_____/|______| |_|    |_|  \_\\____/_/ \_\   |_|   
#                                                                                          
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knowage.proxy.config" . }}
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    user nginx ;
    worker_processes  5 ;
    error_log  /var/log/nginx/error.log ;
    events {
      worker_connections  10240;
    }
    http {
      access_log	/var/log/nginx/access.log ;

      proxy_cache_path   /var/cache/nginx levels=1:2 keys_zone=static-cache:10m max_size=9000g inactive=1d ;
      proxy_temp_path    /var/cache/nginx/tmp ;

      server {
        listen       80;
        server_name  {{ include "knowage.proxy.service" . }};

        # Compression
        gzip on;
        gzip_types text/plain application/xml text/css image/svg+xml;
        
        location / {
          return 301 http://$host/knowage;
        }

        location /knowage {
          proxy_cache static-cache ;
          proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504 ;

          proxy_hide_header Strict-Transport-Security;

          add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0' ;
          add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" ;
          add_header X-Content-Type-Options nosniff ;
          add_header X-Permitted-Cross-Domain-Policies "none" ;

          # Created by: https://report-uri.com/home/generate
          add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; script-src-elem 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://alcdn.msauth.net; style-src 'self' 'unsafe-inline'; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: blob: http://tile.openstreetmap.org http://*.tile.openstreetmap.org http://www.gravatar.com; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://login.microsoftonline.com; object-src 'self'; frame-src 'self' blob: data:; manifest-src 'self'" ;
          add_header Referrer-Policy "no-referrer" ;

          proxy_set_header X-Forwarded-Host $host:$server_port;
          proxy_set_header X-Forwarded-Server $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://{{ include "knowage.service" . }}:8080;
	
          proxy_connect_timeout 60s ;
          proxy_send_timeout    3600s ;
          proxy_read_timeout    3600s ;

          # Caching (browser side)
          if ($request_uri ~* \.(js|css|gif|jpe?g|png|svg|woff2?)) {
            expires 1M;
            add_header Cache-Control "public";
          }
        }

      }
    }
{{ end }}

{{ if eq ( default .Values.knowage.deployHazelcast false ) true }}
#  _    _           ____________ _      _____           _____ _______ 
# | |  | |   /\    |___  /  ____| |    / ____|   /\    / ____|__   __|
# | |__| |  /  \      / /| |__  | |   | |       /  \  | (___    | |   
# |  __  | / /\ \    / / |  __| | |   | |      / /\ \  \___ \   | |   
# | |  | |/ ____ \  / /__| |____| |___| |____ / ____ \ ____) |  | |   
# |_|  |_/_/    \_\/_____|______|______\_____/_/    \_\_____/   |_|   
#                                                                     
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knowage.hazelcast.config" . }}
  namespace: {{ .Release.Namespace }}
data:
  hazelcast.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.6.xsd"
              xmlns="http://www.hazelcast.com/schema/config"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <network>
            <port auto-increment="false" port-count="100">5701</port>
            <join>
                <multicast enabled="false"></multicast>
                <tcp-ip enabled="true">
                    <member-list>
          <member>hazelcast</member>
        </member-list>
                </tcp-ip>
            </join>
        </network>
        <properties> 
          <property name="hazelcast.socket.bind.any">false</property>
        </properties>
    </hazelcast>
{{ end }}
