#
# Knowage, Open Source Business Intelligence suite
# Copyright (C) 2022 Engineering Ingegneria Informatica S.p.A.
# 
# Knowage is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Knowage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

{{ if or (eq ( default .Values.knowage.deployIngress false ) true) (eq ( default .Values.knowage.ingress.deploy false ) true) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{ toYaml .Values.knowage.ingress.annotations | indent 4 }}
  name: {{ include "knowage.ingress" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.knowage.ingress.class }}
  ingressClassName: {{ printf .Values.knowage.ingress.class }}
  {{ end -}}
  rules:
  - host: {{ include "knowage.domain" . }}
    http:
      paths:
      # WARNING : Here we list every context because AWS Load Balancer Controller seems to have
      #  a very strange behavior with pathType equals to Prefix where /knowagecockpitengine, for
      #  example, is not managed by /knowage rule. The Nginx Ingress Controller has the behavior
      #  we expected.
      - backend:
          service:
            name: {{ include "knowage.ingress.service" . }}
            port:
              number: {{ include "knowage.ingress.port" . }}
        path: /knowage
        pathType: Prefix
      - backend:
          service:
            name: {{ include "knowage.ingress.service" . }}
            port:
              number: {{ include "knowage.ingress.port" . }}
        path: /knowage-api
        pathType: Prefix
      - backend:
          service:
            name: {{ include "knowage.ingress.service" . }}
            port:
              number: {{ include "knowage.ingress.port" . }}
        path: /knowage-data-preparation
        pathType: Prefix
      - backend:
          service:
            name: {{ include "knowage.ingress.service" . }}
            port:
              number: {{ include "knowage.ingress.port" . }}
        path: /knowage-vue
        pathType: Prefix
      - backend:
          service:
            name: {{ include "knowage.ingress.service" . }}
            port:
              number: {{ include "knowage.ingress.port" . }}
        path: /knowagebirtreportengine
        pathType: Prefix
      - backend:
          service:
            name: {{ include "knowage.ingress.service" . }}
            port:
              number: {{ include "knowage.ingress.port" . }}
        path: /knowagecockpitengine
        pathType: Prefix
      - backend:
          service:
            name: {{ include "knowage.ingress.service" . }}
            port:
              number: {{ include "knowage.ingress.port" . }}
        path: /knowagegeoreportengine
        pathType: Prefix
      - backend:
          service:
            name: {{ include "knowage.ingress.service" . }}
            port:
              number: {{ include "knowage.ingress.port" . }}
        path: /knowagejasperreportengine
        pathType: Prefix
      - backend:
          service:
            name: {{ include "knowage.ingress.service" . }}
            port:
              number: {{ include "knowage.ingress.port" . }}
        path: /knowagekpiengine
        pathType: Prefix
      - backend:
          service:
            name: {{ include "knowage.ingress.service" . }}
            port:
              number: {{ include "knowage.ingress.port" . }}
        path: /knowagemeta
        pathType: Prefix
      - backend:
          service:
            name: {{ include "knowage.ingress.service" . }}
            port:
              number: {{ include "knowage.ingress.port" . }}
        path: /knowageqbeengine
        pathType: Prefix
      - backend:
          service:
            name: {{ include "knowage.ingress.service" . }}
            port:
              number: {{ include "knowage.ingress.port" . }}
        path: /knowagesvgviewerengine
        pathType: Prefix
      - backend:
          service:
            name: {{ include "knowage.ingress.service" . }}
            port:
              number: {{ include "knowage.ingress.port" . }}
        path: /knowagewhatifengine
        pathType: Prefix
  tls:
    - hosts:
      - {{ include "knowage.domain" . }}
      # secretName: {{ include "knowage.tls" . }}
{{ end }}
