#
# Knowage, Open Source Business Intelligence suite
# Copyright (C) 2022 Engineering Ingegneria Informatica S.p.A.
# 
# Knowage is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Knowage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

{{ if eq ( default .Values.knowage.deployIngress false ) true }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/app-root: "/knowage"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    # User must use the same node everytime
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"
    nginx.ingress.kubernetes.io/session-cookie-samesite: "Strict"
    nginx.ingress.kubernetes.io/session-cookie-conditional-samesite-none: "true"
    nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "true"
    # 
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Compression
      gzip on;
      gzip_types text/plain application/xml text/css image/svg+xml;

      # Reverse proxy header
      proxy_set_header X-Forwarded-Host $host:$server_port;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # Security header
      # WARNING: actually, a bug send also another Strict-Transport-Security but the following is the correct one
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" ;
      add_header X-Content-Type-Options nosniff ;
      add_header X-Permitted-Cross-Domain-Policies "none" ;
      add_header Content-Security-Policy "default-src 'self'; connect-src 'self' https://login.microsoftonline.com; manifest-src 'self'; object-src 'self'; frame-src 'self' blob: data:; font-src 'self' data:; img-src 'self' blob: data: http://tile.openstreetmap.org  http://*.tile.openstreetmap.org http://www.gravatar.com; script-src 'self' 'unsafe-eval' 'unsafe-inline'; script-src-elem 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://alcdn.msauth.net; style-src 'self' 'unsafe-inline'; style-src-elem 'self' 'unsafe-inline'" ;
      add_header Referrer-Policy "no-referrer" ;
  name: {{ include "knowage.ingress" . }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ include "knowage.domain" . }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "knowage.python.service" . }}
            port:
              number: 5000
        path: /knowagewidget
        pathType: Prefix
      - backend:
          service:
            name: {{ include "knowage.service" . }}
            port:
              name: https
        path: /knowage
        pathType: Prefix
  tls:
    - hosts:
      - {{ include "knowage.domain" . }}
      secretName: {{ include "knowage.tls" . }}
{{ end }}
