{{- if .Values.knowage.priorityClasses.enabled -}}
---
#  _____  _____  _____ __  __          _______     __
# |  __ \|  __ \|_   _|  \/  |   /\   |  __ \ \   / /
# | |__) | |__) | | | | \  / |  /  \  | |__) \ \_/ / 
# |  ___/|  _  /  | | | |\/| | / /\ \ |  _  / \   /  
# | |    | | \ \ _| |_| |  | |/ ____ \| | \ \  | |   
# |_|    |_|  \_\_____|_|  |_/_/    \_\_|  \_\ |_|   
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "knowage.priorityclass.primary" . }}
  namespace: {{ .Release.Namespace }}
value: 1000000
globalDefault: false
description: "Primary level app for KNOWAGE"
preemptionPolicy: PreemptLowerPriority
---
#   _____ ______ _____ ____  _   _ _____          _______     __
#  / ____|  ____/ ____/ __ \| \ | |  __ \   /\   |  __ \ \   / /
# | (___ | |__ | |   | |  | |  \| | |  | | /  \  | |__) \ \_/ / 
#  \___ \|  __|| |   | |  | | . ` | |  | |/ /\ \ |  _  / \   /  
#  ____) | |___| |___| |__| | |\  | |__| / ____ \| | \ \  | |   
# |_____/|______\_____\____/|_| \_|_____/_/    \_\_|  \_\ |_|   
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "knowage.priorityclass.secondary" . }}
  namespace: {{ .Release.Namespace }}
value: 1000001
globalDefault: false
description: "Secondary level app for KNOWAGE"
preemptionPolicy: PreemptLowerPriority
{{ end }}
