#
# Knowage, Open Source Business Intelligence suite
# Copyright (C) 2022 Engineering Ingegneria Informatica S.p.A.
# 
# Knowage is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Knowage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

---
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "knowage-db-secret" ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knowage.db.secret" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
{{ if $secret -}}
data:
  dbUser:     {{ $secret.data.dbUser }}
  dbPass:     {{ $secret.data.dbPass }}
  dbRootPass: {{ $secret.data.dbRootPass }}
  dbDb:       {{ $secret.data.dbDb }}
{{ else -}}
stringData:
  dbUser:     "{{ .Values.knowage.db.user }}"
  dbPass:     "{{ default ( randAlphaNum 32 ) .Values.knowage.db.pass }}"
  dbRootPass: "{{ default ( randAlphaNum 32 ) .Values.knowage.db.rootPass  }}"
  dbDb:       "{{ .Values.knowage.db.name }}"
{{ end }}
---
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "knowage-cache-db-secret" ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knowage.cache.secret" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
{{ if $secret -}}
data:
  dbUser: {{ $secret.data.dbUser }}
  dbPass: {{ $secret.data.dbPass }}
  dbRootPass: {{ $secret.data.dbRootPass }}
  dbDb: {{ $secret.data.dbDb }}
{{ else -}}
stringData:
  dbUser: "{{ .Values.knowage.cache.user }}"
  dbPass: "{{ default ( randAlphaNum 32 ) .Values.knowage.cache.pass }}"
  dbRootPass: "{{ default ( randAlphaNum 32 ) .Values.knowage.cache.rootPass }}"
  dbDb: "{{ .Values.knowage.cache.name }}"
{{ end }}
---
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "knowage-secret" ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knowage.secret" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
{{ if $secret -}}
data:
  hmac: {{ $secret.data.hmac }}
  passwordEncryptionSecret: {{ $secret.data.passwordEncryptionSecret }}
{{ else -}}
stringData:
  hmac: "{{ default ( randAlphaNum 32 ) .Values.knowage.hmac }}"
  passwordEncryptionSecret: "{{ default ( randAlphaNum 32 ) .Values.knowage.passwordEncryptionSecret }}"
{{ end }}
