#
# Knowage, Open Source Business Intelligence suite
# Copyright (C) 2023 Engineering Ingegneria Informatica S.p.A.
# 
# Knowage is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Knowage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

{{ if eq ( default .Values.knowage.deployCustomReverseProxy false ) true }}
---
#  _____  ________      ________ _____   _____ ______   _____  _____   ______   ____     __
# |  __ \|  ____\ \    / /  ____|  __ \ / ____|  ____| |  __ \|  __ \ / __ \ \ / /\ \   / /
# | |__) | |__   \ \  / /| |__  | |__) | (___ | |__    | |__) | |__) | |  | \ V /  \ \_/ / 
# |  _  /|  __|   \ \/ / |  __| |  _  / \___ \|  __|   |  ___/|  _  /| |  | |> <    \   /  
# | | \ \| |____   \  /  | |____| | \ \ ____) | |____  | |    | | \ \| |__| / . \    | |   
# |_|  \_\______|   \/   |______|_|  \_\_____/|______| |_|    |_|  \_\\____/_/ \_\   |_|   
#                                                                                          
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knowage.tls.proxy.name" . }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
{{ ( include "knowage.tls.proxy.cert" . ) | indent 2 -}}
{{ end }}

---
#  __  __          _____ _   _            _____  _____  
# |  \/  |   /\   |_   _| \ | |     /\   |  __ \|  __ \ 
# | \  / |  /  \    | | |  \| |    /  \  | |__) | |__) |
# | |\/| | / /\ \   | | | . ` |   / /\ \ |  ___/|  ___/ 
# | |  | |/ ____ \ _| |_| |\  |  / ____ \| |    | |     
# |_|  |_/_/    \_\_____|_| \_| /_/    \_\_|    |_|     
#                                                       
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knowage.tls.main.name" . }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
{{ ( include "knowage.tls.main.cert" . ) | indent 2 -}}
