#
# Knowage, Open Source Business Intelligence suite
# Copyright (C) 2021 Engineering Ingegneria Informatica S.p.A.
# 
# Knowage is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Knowage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#  __  __          _____ _   _            _____  _____  
# |  \/  |   /\   |_   _| \ | |     /\   |  __ \|  __ \ 
# | \  / |  /  \    | | |  \| |    /  \  | |__) | |__) |
# | |\/| | / /\ \   | | | . ` |   / /\ \ |  ___/|  ___/ 
# | |  | |/ ____ \ _| |_| |\  |  / ____ \| |    | |     
# |_|  |_/_/    \_\_____|_| \_| /_/    \_\_|    |_|     
#                                                       
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knowage.config" . }}
data:
  dbHost: {{ include "knowage.db.service" . | quote }}
  dbPort: "3306"
  cacheDbHost: {{ include "knowage.cache.service" . | quote }}
  cacheDbPort: "3306"

{{ if eq ( default .Values.knowage.deployCustomReverseProxy false ) true }}
#  _____  ________      ________ _____   _____ ______   _____  _____   ______   ____     __
# |  __ \|  ____\ \    / /  ____|  __ \ / ____|  ____| |  __ \|  __ \ / __ \ \ / /\ \   / /
# | |__) | |__   \ \  / /| |__  | |__) | (___ | |__    | |__) | |__) | |  | \ V /  \ \_/ / 
# |  _  /|  __|   \ \/ / |  __| |  _  / \___ \|  __|   |  ___/|  _  /| |  | |> <    \   /  
# | | \ \| |____   \  /  | |____| | \ \ ____) | |____  | |    | | \ \| |__| / . \    | |   
# |_|  \_\______|   \/   |______|_|  \_\_____/|______| |_|    |_|  \_\\____/_/ \_\   |_|   
#                                                                                          
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knowage.proxy.config" . }}
data:
  nginx.conf: |
    user nginx ;
    worker_processes  5 ;
    error_log  /var/log/nginx/error.log ;
    events {
      worker_connections  10240;
    }
    http {
      access_log	/var/log/nginx/access.log ;

      proxy_cache_path   /var/cache/nginx levels=1:2 keys_zone=static-cache:10m max_size=9000g inactive=1d ;
      proxy_temp_path    /var/cache/nginx/tmp ;

      server {
        listen       80;
        server_name  {{ include "knowage.proxy.service" . }};

        # Compression
        gzip on;
        gzip_types text/plain application/xml text/css image/svg+xml;
        
        location / {
          return 301 http://$host/knowage;
        }

        location /knowage {
          proxy_cache static-cache ;
          proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504 ;

          proxy_hide_header Strict-Transport-Security;

          add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0' ;
          add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" ;
          add_header X-Content-Type-Options nosniff ;
          add_header X-Permitted-Cross-Domain-Policies "none" ;
          add_header Content-Security-Policy "default-src 'self'; connect-src 'self'; manifest-src 'self'; object-src 'self'; frame-src 'self' blob:; font-src 'self' data:; img-src 'self' data: http://tile.openstreetmap.org  http://*.tile.openstreetmap.org; script-src 'self' 'unsafe-eval' 'unsafe-inline'; script-src-elem 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline'; style-src-elem 'self' 'unsafe-inline'" ;
          add_header Referrer-Policy "no-referrer" ;

          proxy_set_header X-Forwarded-Host $host:$server_port;
          proxy_set_header X-Forwarded-Server $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://{{ include "knowage.service" . }}:8080;
        }

        location /knowagewidget {
          proxy_set_header X-Forwarded-Host $host:$server_port;
          proxy_set_header X-Forwarded-Server $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_pass http://{{ include "knowage.python.service" . }}:5000;
        }
      }
    }
{{ end }}
