#
# Knowage, Open Source Business Intelligence suite
# Copyright (C) 2021 Engineering Ingegneria Informatica S.p.A.
# 
# Knowage is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Knowage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#  __  __          _____ _   _            _____  _____  
# |  \/  |   /\   |_   _| \ | |     /\   |  __ \|  __ \ 
# | \  / |  /  \    | | |  \| |    /  \  | |__) | |__) |
# | |\/| | / /\ \   | | | . ` |   / /\ \ |  ___/|  ___/ 
# | |  | |/ ____ \ _| |_| |\  |  / ____ \| |    | |     
# |_|  |_/_/    \_\_____|_| \_| /_/    \_\_|    |_|     
#                                                       
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knowage.deployment" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      knowage-suite.com/app: knowage
      {{- include "knowage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        knowage-suite.com/app: knowage
        {{- include "knowage.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "knowage.pod" . }}
        image: "knowagelabs/knowage-server-docker:{{ .Values.knowage.tag }}"
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.db.secret" . }}
                key: dbUser
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.db.secret" . }}
                key: dbPass
          - name: DB_DB
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.db.secret" . }}
                key: dbDb
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ include "knowage.config" . }}
                key: dbHost
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ include "knowage.config" . }}
                key: dbPort

          - name: CACHE_DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.cache.secret" . }}
                key: dbUser
          - name: CACHE_DB_PASS
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.cache.secret" . }}
                key: dbPass
          - name: CACHE_DB_DB
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.cache.secret" . }}
                key: dbDb
          - name: CACHE_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ include "knowage.config" . }}
                key: cacheDbHost
          - name: CACHE_DB_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ include "knowage.config" . }}
                key: cacheDbPort

          - name: HMAC_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.secret" . }}
                key: hmac
          - name: PASSWORD_ENCRYPTION_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.secret" . }}
                key: passwordEncryptionSecret
        livenessProbe:
          httpGet:
            path: /knowage/restful-services/version
            port: 8080
          initialDelaySeconds: 120
          failureThreshold: 5
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /knowage/restful-services/version
            port: 8080
          initialDelaySeconds: 120
          failureThreshold: 5
          periodSeconds: 30
        ports:
          - name: main
            containerPort: 8080
            protocol: TCP
        volumeMounts:
        - name: resources
          mountPath: /home/knowage/apache-tomcat/resources
      volumes:
      - name: resources
        persistentVolumeClaim:
          claimName: {{ include "knowage.pvc" . }}



#  __  __           _____ _______ ______ _____    _____  ____  
# |  \/  |   /\    / ____|__   __|  ____|  __ \  |  __ \|  _ \ 
# | \  / |  /  \  | (___    | |  | |__  | |__) | | |  | | |_) |
# | |\/| | / /\ \  \___ \   | |  |  __| |  _  /  | |  | |  _ < 
# | |  | |/ ____ \ ____) |  | |  | |____| | \ \  | |__| | |_) |
# |_|  |_/_/    \_\_____/   |_|  |______|_|  \_\ |_____/|____/ 
#                                                              
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "knowage.db.deployment" . }}
spec:
  serviceName: "knowage-db"
  replicas: 1
  selector:
    matchLabels:
      knowage-suite.com/app: knowagedb
      {{- include "knowage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        knowage-suite.com/app: knowagedb
        {{- include "knowage.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: {{ include "knowage.db.pod" . }}
        image: mariadb:10.3
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.db.secret" . }}
                key: dbUser
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.db.secret" . }}
                key: dbPass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.db.secret" . }}
                key: dbRootPass
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.db.secret" . }}
                key: dbDb
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
        ports:
          - name: main
            containerPort: 3306
            protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "knowage.db.pvc" . }}


#   _____          _____ _    _ ______   _____  ____  
#  / ____|   /\   / ____| |  | |  ____| |  __ \|  _ \ 
# | |       /  \ | |    | |__| | |__    | |  | | |_) |
# | |      / /\ \| |    |  __  |  __|   | |  | |  _ < 
# | |____ / ____ \ |____| |  | | |____  | |__| | |_) |
#  \_____/_/    \_\_____|_|  |_|______| |_____/|____/ 
#                                                     
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "knowage.cache.deployment" . }}
spec:
  serviceName: "knowage-cache-db"
  replicas: 1
  selector:
    matchLabels:
      knowage-suite.com/app: knowagecachedb
      {{- include "knowage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        knowage-suite.com/app: knowagecachedb
        {{- include "knowage.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: {{ include "knowage.cache.pod" . }}
        image: mariadb:10.3
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.cache.secret" . }}
                key: dbUser
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.cache.secret" . }}
                key: dbPass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.cache.secret" . }}
                key: dbRootPass
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.cache.secret" . }}
                key: dbDb
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
        ports:
          - name: main
            containerPort: 3306
            protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "knowage.cache.pvc" . }}



{{ if eq ( default .Values.knowage.installSampleData false ) true }}
#  ______ ____   ____  _____  __  __          _____ _______ 
# |  ____/ __ \ / __ \|  __ \|  \/  |   /\   |  __ \__   __|
# | |__ | |  | | |  | | |  | | \  / |  /  \  | |__) | | |   
# |  __|| |  | | |  | | |  | | |\/| | / /\ \ |  _  /  | |   
# | |   | |__| | |__| | |__| | |  | |/ ____ \| | \ \  | |   
# |_|    \____/ \____/|_____/|_|  |_/_/    \_\_|  \_\ |_|   
#                                                           
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knowage.foodmart.deployment" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      knowage-suite.com/app: foodmart
      {{- include "knowage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        knowage-suite.com/app: foodmart
        {{- include "knowage.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "knowage.foodmart.pod" . }}
        image: "m20tech/mysql-foodmart"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
        ports:
          - name: main
            containerPort: 3306
            protocol: TCP
{{ end }}

#  _______     _________ _    _  ____  _   _ 
# |  __ \ \   / /__   __| |  | |/ __ \| \ | |
# | |__) \ \_/ /   | |  | |__| | |  | |  \| |
# |  ___/ \   /    | |  |  __  | |  | | . ` |
# | |      | |     | |  | |  | | |__| | |\  |
# |_|      |_|     |_|  |_|  |_|\____/|_| \_|
#                                            
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knowage.python.deployment" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      knowage-suite.com/app: knowage-python
      {{- include "knowage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        knowage-suite.com/app: knowage-python
        {{- include "knowage.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "knowage.python.pod" . }}
        image: "knowagelabs/knowage-python-docker:{{ .Values.knowage.tag }}"
        imagePullPolicy: IfNotPresent
        env:
          - name: HMAC_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.secret" . }}
                key: hmac
          - name: KNOWAGE_PUBLIC_ADDRESS
            value: {{ include "knowage.service" . }}
          - name: PUBLIC_ADDRESS
            value: {{ include "knowage.python.service" . }}
        livenessProbe:
          httpGet:
            path: /dataset/libraries
            port: 5000
          initialDelaySeconds: 10
          failureThreshold: 5
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /dataset/libraries
            port: 5000
          initialDelaySeconds: 10
          failureThreshold: 5
          periodSeconds: 1
        ports:
          - name: main
            containerPort: 5000
            protocol: TCP



#  _____  
# |  __ \ 
# | |__) |
# |  _  / 
# | | \ \ 
# |_|  \_\
#         
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knowage.r.deployment" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      knowage-suite.com/app: knowage-r
      {{- include "knowage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        knowage-suite.com/app: knowage-r
        {{- include "knowage.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "knowage.r.pod" . }}
        image: "knowagelabs/knowage-r-docker:{{ .Values.knowage.tag }}"
        imagePullPolicy: IfNotPresent
        env:
          - name: HMAC_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "knowage.secret" . }}
                key: hmac
        livenessProbe:
          httpGet:
            path: /dataset/libraries
            port: 5001
          initialDelaySeconds: 10
          failureThreshold: 5
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /dataset/libraries
            port: 5001
          initialDelaySeconds: 10
          failureThreshold: 5
          periodSeconds: 1
        ports:
          - name: main
            containerPort: 5001
            protocol: TCP
