#
# Knowage, Open Source Business Intelligence suite
# Copyright (C) 2021 Engineering Ingegneria Informatica S.p.A.
# 
# Knowage is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Knowage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

{{ if eq ( default .Values.knowage.deployIngress false ) true }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "knowage.ingress" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/app-root: "/knowage"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    # TODO : we cannot do that here
    # nginx.ingress.kubernetes.io/http-snippet: |
    #   proxy_cache_path /tmp/nginx-cache levels=1:2 keys_zone=static-cache:2m max_size=100m inactive=7d use_temp_path=off;
    #   proxy_cache_key $scheme$proxy_host$request_uri;
    #   proxy_cache_lock on;
    #   proxy_cache_use_stale updating;
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Compression
      gzip on;
      gzip_types text/plain application/xml text/css image/svg+xml;

      # TODO
      # # Cache
      # proxy_cache static-cache ;
      # proxy_cache_valid 404 1m ;
      # proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504 ;
      # proxy_cache_bypass $http_x_purge ;
      # add_header X-Cache-Status $upstream_cache_status ;
      
      # Reverse proxy header
      proxy_set_header X-Forwarded-Host $host:$server_port;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # Security header
      add_header Cache-Control "max-age=2592000 must-revalidate" ;
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" ;
      add_header X-Content-Type-Options nosniff ;
      add_header X-Permitted-Cross-Domain-Policies "none" ;
      add_header Content-Security-Policy "default-src 'none'; connect-src 'self' {{ print .Values.knowage.completeExternalUrl }}; manifest-src 'self' {{ print .Values.knowage.completeExternalUrl }}; object-src 'self' {{ print .Values.knowage.completeExternalUrl }}; frame-src 'self' {{ print .Values.knowage.completeExternalUrl }}; font-src 'self' data:; img-src 'self' data: http://tile.openstreetmap.org  http://*.tile.openstreetmap.org; script-src 'unsafe-eval' 'unsafe-inline' {{ print .Values.knowage.completeExternalUrl }}; script-src-elem 'unsafe-inline' {{ print .Values.knowage.completeExternalUrl }} https://cdnjs.cloudflare.com; style-src 'unsafe-inline' {{ print .Values.knowage.completeExternalUrl }}; style-src-elem 'unsafe-inline' {{ print .Values.knowage.completeExternalUrl }}" ;
      add_header Referrer-Policy "no-referrer" ;
spec:
  rules:
  - host: {{ include "knowage.domain" . }}
    http:
      paths:
      - backend:
          serviceName: {{ include "knowage.service" . }}
          servicePort: 8080
        path: /knowage
      - backend:
          serviceName: {{ include "knowage.python.service" . }}
          servicePort: 5000
        path: /knowagewidget
  tls:
    - hosts:
      - {{ include "knowage.domain" . }}
      secretName: {{ include "knowage.tls" . }}
{{ end }}
