#
# Knowage, Open Source Business Intelligence suite
# Copyright (C) 2021 Engineering Ingegneria Informatica S.p.A.
# 
# Knowage is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Knowage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#  __  __          _____ _   _            _____  _____  
# |  \/  |   /\   |_   _| \ | |     /\   |  __ \|  __ \ 
# | \  / |  /  \    | | |  \| |    /  \  | |__) | |__) |
# | |\/| | / /\ \   | | | . ` |   / /\ \ |  ___/|  ___/ 
# | |  | |/ ____ \ _| |_| |\  |  / ____ \| |    | |     
# |_|  |_/_/    \_\_____|_| \_| /_/    \_\_|    |_|     
#                                                       
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "knowage.service" . }}
spec:
  type: NodePort
  selector:
    knowage-suite.com/app: knowage
    {{- include "knowage.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32020



#  __  __           _____ _______ ______ _____    _____  ____  
# |  \/  |   /\    / ____|__   __|  ____|  __ \  |  __ \|  _ \ 
# | \  / |  /  \  | (___    | |  | |__  | |__) | | |  | | |_) |
# | |\/| | / /\ \  \___ \   | |  |  __| |  _  /  | |  | |  _ < 
# | |  | |/ ____ \ ____) |  | |  | |____| | \ \  | |__| | |_) |
# |_|  |_/_/    \_\_____/   |_|  |______|_|  \_\ |_____/|____/ 
#                                                              
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "knowage.db.service" . }}
spec:
  selector:
    knowage-suite.com/app: knowagedb
    {{- include "knowage.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306



#   _____          _____ _    _ ______   _____  ____  
#  / ____|   /\   / ____| |  | |  ____| |  __ \|  _ \ 
# | |       /  \ | |    | |__| | |__    | |  | | |_) |
# | |      / /\ \| |    |  __  |  __|   | |  | |  _ < 
# | |____ / ____ \ |____| |  | | |____  | |__| | |_) |
#  \_____/_/    \_\_____|_|  |_|______| |_____/|____/ 
#                                                     
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "knowage.cache.service" . }}
spec:
  selector:
    knowage-suite.com/app: knowagecachedb
    {{- include "knowage.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306



{{ if eq ( default .Values.knowage.installSampleData false ) true }}
#  ______ ____   ____  _____  __  __          _____ _______ 
# |  ____/ __ \ / __ \|  __ \|  \/  |   /\   |  __ \__   __|
# | |__ | |  | | |  | | |  | | \  / |  /  \  | |__) | | |   
# |  __|| |  | | |  | | |  | | |\/| | / /\ \ |  _  /  | |   
# | |   | |__| | |__| | |__| | |  | |/ ____ \| | \ \  | |   
# |_|    \____/ \____/|_____/|_|  |_/_/    \_\_|  \_\ |_|   
#                                                           
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "knowage.foodmart.service" . }}
spec:
  selector:
    knowage-suite.com/app: foodmart
    {{- include "knowage.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
{{ end }}



#  _______     _________ _    _  ____  _   _ 
# |  __ \ \   / /__   __| |  | |/ __ \| \ | |
# | |__) \ \_/ /   | |  | |__| | |  | |  \| |
# |  ___/ \   /    | |  |  __  | |  | | . ` |
# | |      | |     | |  | |  | | |__| | |\  |
# |_|      |_|     |_|  |_|  |_|\____/|_| \_|
#                                            
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "knowage.python.service" . }}
spec:
  selector:
    knowage-suite.com/app: knowage-python
    {{- include "knowage.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000



#  _____  
# |  __ \ 
# | |__) |
# |  _  / 
# | | \ \ 
# |_|  \_\
#         
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "knowage.r.service" . }}
spec:
  selector:
    knowage-suite.com/app: knowage-r
    {{- include "knowage.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
