name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 3.8.3 not found
        version: [ "3.7.2", "3.8.2", "3.9.4", "3.10.2", "3.11.3", "3.12.3", "3.13.3", "3.14.4" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: ${{ matrix.version }}

      - name: Run Helm Template
        run: |
          cd charts/knowage
          helm template test .

  release:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
